#!/bin/bash

build() {
    local applet

    for x in awk basename blkid cat chmod chown chroot clear cp cut dd dirname dmesg du echo egrep expr false grep halt head init install ip kbd_mode kill less ln losetup ls mg mkdir mkfifo mksh mktemp mount mv nc openvt pidof poweroff pwd reboot rm sed seq setfont sh sleep sort switch_root tail test touch true umount uname uniq vi wc yes; do
        add_file $(which x) /bin/$x
    done

    # add kmod with applet symlinks
    add_file kmod
    for applet in {dep,ins,rm,ls}mod mod{probe,info}; do
        add_symlink "/usr/bin/$applet" kmod
    done

    add_file "/usr/lib/initcpio/init_functions" "/init_functions"
    add_file "/usr/lib/initcpio/init" "/init"
    add_file "/usr/lib/modprobe.d/usb-load-ehci-first.conf"
}

help() {
    cat <<HELPEOF
This hook provides crucial runtime necessities for booting. DO NOT
remove this hook unless you know what you're doing.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
